name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build_ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Just
        run: cargo install just

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: just release

      - name: Install ctags on Linux
        run: |
          sudo apt-get update
          sudo apt-get install exuberant-ctags

      - name: Zip Plugins
        run: |
          zip --junk-paths coco_plugins target/release/libcoco_swagger.so target/release/libcoco_struct_analysis.so target/release/libcoco_coverage.so

      - name: Upload visual to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/visual
          asset_name: visual_linux
          tag: ${{ github.ref }}

      - name: Upload coco to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/coco
          asset_name: coco_linux
          tag: ${{ github.ref }}

      - name: Upload plugins to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: coco_plugins.zip
          asset_name: coco_plugins_linux.zip
          tag: ${{ github.ref }}

  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Just
        run: cargo install just

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: just release

      - name: Install ctags on Windows
        run: |
          choco install universal-ctags

      - name: Zip Plugins
        run: |
          powershell Compress-Archive -Path target\release\coco_swagger.dll,target\release\coco_struct_analysis.dll,target\release\coco_coverage.dll -DestinationPath windows.zip

      - name: Upload visual to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/visual.exe
          asset_name: visual-windows.exe
          tag: ${{ github.ref }}

      - name: Upload coco to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/coco.exe
          asset_name: coco-windows.exe
          tag: ${{ github.ref }}

      - name: Upload plugins to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: coco_plugins.zip
          asset_name: coco_plugins_windows.zip
          tag: ${{ github.ref }}

  build_macOS:
    name: Build macOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Just
        run: cargo install just

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: just release

      - name: Install ctags on Windows
        run: |
          brew update
          brew install --HEAD universal-ctags/universal-ctags/universal-ctags

      - name: Zip Plugins
        run: |
          zip --junk-paths coco_plugins target/release/libcoco_swagger.dylib target/release/libcoco_struct_analysis.dylib target/release/libcoco_coverage.dylib

      - name: Upload visual to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/visual
          asset_name: visual_macos
          tag: ${{ github.ref }}

      - name: Upload coco to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/coco
          asset_name: coco_macos
          tag: ${{ github.ref }}

      - name: Upload plugins to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: coco_plugins.zip
          asset_name: coco_plugins_macos.zip
          tag: ${{ github.ref }}
